module.exports = [
  
    "Java","Spring Boot","Spring","Spring MVC","Spring Security","Hibernate",
    "Python","Django","Flask","FastAPI",
    "C","C++","C#",".NET",".NET Core",
    "Go","Rust","Scala","Kotlin","Swift",
    "JavaScript","TypeScript","Node.js","Express.js","NestJS",
    "Angular","React","Vue.js","Next.js","Nuxt.js","Svelte",
    "HTML","HTML5","CSS","CSS3","SASS","LESS","Tailwind CSS","Bootstrap",
    "Material UI","Redux","RxJS",
    "SQL","MySQL","PostgreSQL","SQLite","Oracle DB","Microsoft SQL Server",
    "DB2","MariaDB",
    "MongoDB","Redis","Cassandra","CouchDB","Neo4j","Firebase","DynamoDB",
    "NoSQL",
    "REST API","GraphQL","gRPC","SOAP",
    "Microservices","Monolithic Architecture","Event Driven Architecture",
    "Distributed Systems","System Design",
    "Docker","Kubernetes","Helm","Podman","Containerization",
    "Linux","Unix","Ubuntu","RedHat","Debian",
    "Bash","Shell Scripting","PowerShell",
    "Git","GitHub","GitLab","Bitbucket",
    "CI/CD","Jenkins","GitHub Actions","GitLab CI","CircleCI","Travis CI",
    "Azure DevOps",
    "Terraform","Ansible","Chef","Puppet",
    "AWS","Amazon EC2","Amazon S3","AWS Lambda","AWS RDS","AWS DynamoDB",
    "AWS CloudFormation","AWS ECS","AWS EKS",
    "Microsoft Azure","Azure Functions","Azure Storage","Azure SQL",
    "Google Cloud","Google Kubernetes Engine","Google BigQuery",
    "Cloud Computing","Serverless Computing","Edge Computing",
    "Kafka","RabbitMQ","ActiveMQ","ZeroMQ","Amazon SQS",
    "Apache Spark","Hadoop","Hive","Presto","Flink","Airflow",
    "ETL","Data Engineering","Big Data","Data Warehousing",
    "Machine Learning","Deep Learning","Artificial Intelligence",
    "TensorFlow","PyTorch","Keras","Scikit Learn",
    "Natural Language Processing","Computer Vision",
    "Pandas","NumPy","Matplotlib","Seaborn",
    "Tableau","Power BI","Looker",
    "Cybersecurity","Information Security","Penetration Testing",
    "Ethical Hacking","Network Security","Application Security",
    "Encryption","OAuth","JWT","SAML",
    "Unit Testing","Integration Testing","JUnit","Mockito",
    "Selenium","Cypress","Playwright","Jest","Mocha","Chai",
    "Load Testing","Performance Testing",
    "Prometheus","Grafana","ELK Stack","Logstash","Kibana",
    "OpenTelemetry","Monitoring","Logging","Observability",
    "Agile","Scrum","Kanban","SAFe","Waterfall",
    "Project Management","Product Management",
    "Software Development Lifecycle","SDLC",
    "Debugging","Code Review","Refactoring",
    "Performance Optimization","Scalability","Reliability","Fault Tolerance",
    "Communication","Teamwork","Leadership","Problem Solving",
    "Critical Thinking","Time Management","Adaptability",
    "Creativity","Decision Making","Collaboration",
    "Conflict Resolution","Negotiation","Emotional Intelligence",
    "Accountability","Presentation Skills","Active Listening",
    "Interpersonal Skills","Customer Focus",
    "Mentoring","Strategic Thinking","Innovation",
    "Work Ethic","Attention to Detail","node","express","react","angular","vue","django","flask","devops","aws","azure","gcp","docker","kubernetes", 
    "microservices","graphql","rest api","devdelopment","testing","ci/cd","agile","scrum","kanban","project management",
    "communication","teamwork","leadership","problem solving","critical thinking",
    "time management","adaptability","creativity","decision making","collaboration","develop","design","build","maintain","optimize","debug","refactor","code review",
    "debuggoing","performance optimization","scalability","reliability","fault tolerance",
    "communication","teamwork","leadership","problem solving","critical thinking",
    "time management","adaptability","creativity","decision making","collaboration", "mentoring","strategic thinking","innovation","work ethic","attention to detail",
     "AI","Machine Learning","Deep Learning","Natural Language Processing","Computer Vision",
     "TensorFlow","PyTorch","Keras","Scikit Learn",
     "Pandas","NumPy","Matplotlib","Seaborn",
     "Tableau","Power BI","Looker","Cybersecurity","Information Security","Penetration Testing",
     "Ethical Hacking","Network Security","Application Security",
     "Encryption","OAuth","JWT","SAML","Unit Testing","Integration Testing","JUnit","Mockito",
     "Selenium","Cypress","Playwright","Jest","Mocha","Chai",
     "Load Testing","Performance Testing","Prometheus","Grafana","ELK Stack","Logstash","Kibana",
     "OpenTelemetry","Monitoring","Logging","Observability",
     "Agile","Scrum","Kanban","SAFe","Waterfall","Project Management","Product Management","Software Development Lifecycle","SDLC",
     "Debugging","Code Review","Refactoring","Performance Optimization","Scalability","Reliability","Fault Tolerance",
     "Communication","Teamwork","Leadership","Problem Solving","Critical Thinking","Time Management","Adaptability","Creativity","Decision Making","Collaboration",
     "Conflict Resolution","Negotiation","Emotional Intelligence","Accountability","Presentation Skills","Active Listening","Interpersonal Skills","Customer Focus",
     "Mentoring","Strategic Thinking","Innovation","Work Ethic","Attention to Detail","Artificial Intelligence","Data Science","Data Analysis","Data Visualization","Big Data","Cloud Computing","DevOps","Microservices","Containerization",
     "Serverless Computing","Edge Computing","Distributed Systems","System Design","Kafka","RabbitMQ","ActiveMQ","ZeroMQ","Amazon SQS",
     "Apache Spark","Hadoop","Hive","Presto","Flink","Airflow","ETL","Data Engineering","Big Data","Data Warehousing",
     "Machine Learning","Deep Learning","Artificial Intelligence","Artifical intelligence","hibernate","spring boot","spring security","spring mvc","python","django","flask","fastapi","c","c++","c#",".net",".net core","go","rust","scala","kotlin","swift","javascript","typescript","node.js","express.js","nestjs","angular","react","vue.js","next.js","nuxt.js","svelte",
     "html","html5","css","css3","sass","less","tailwind css","bootstrap",
     "material ui","redux","rxjs",
    ]

